---
- name: System | Restart atd
  service:
    name: atd
    state: stopped
    enabled: no
  ignore_errors: true
  tags: system

- name: System | Copy Chrony files
  template:
    src:         templates/{{ item }}.j2
    dest:        /etc/{{ item }}
    owner:       root
    group:       root
    mode:        "0644"
  with_items:
    - chrony.conf
    - chrony.keys
  tags: system

- name: System | Restart chronyd
  service:
    name: chronyd
    state: restarted
  tags: system

- name: System | Test for crypto_policy group
  command: grep '^\s*\[\s*crypto_policy\s*]' /etc/pki/tls/openssl.cnf
  register: test_crypto_policy_group
  ignore_errors: true
  changed_when: false
  check_mode: false
  tags: system

- name: System | Add .include for opensslcnf.config to crypto_policy section
  lineinfile:
    create: true
    insertafter: ^\s*\[\s*crypto_policy\s*]\s*
    line: .include /etc/crypto-policies/back-ends/opensslcnf.config
    path: /etc/pki/tls/openssl.cnf
  when:
    - test_crypto_policy_group.stdout is defined
    - test_crypto_policy_group.stdout | length > 0
  tags: system

- name: System | Add crypto_policy group and set include opensslcnf.config
  lineinfile:
    create: true
    line: |-
      [crypto_policy]
      .include /etc/crypto-policies/back-ends/opensslcnf.config
    path: /etc/pki/tls/openssl.cnf
  when:
    - test_crypto_policy_group.stdout is defined
    - test_crypto_policy_group.stdout | length < 1
  tags: system
...
