---
- name: Create user group
  ansible.builtin.group:
    name:     "{{ k3s_group }}"
    state:    present
    gid:      "{{ k3s_gid }}"

- name: Create user
  ansible.builtin.user:
    name:     "{{ k3s_user }}"
    shell:    /bin/bash
    createhome: yes
    comment:  Kubernetes Admin
    uid:      "{{ k3s_uid }}"
    group:    k3s
    #password: "$6$ukHvWiNPJEp0tirg$6bZdufYRIAf9iXgrRntgJk0lJWgGvPBVLfnBt5ffkNOGc8Ew5SGJqglu7PWSQPZ57Z8TdyDWOhZa0cvAORKqu/"

    password: "{{ k3s_passwd | password_hash('sha512') }}"
    state:    present

- name: Create a 2048-bit SSH key for user k3s in ~k3s/.ssh/id_rsa
  ansible.builtin.user:
    name:     k3s
    generate_ssh_key: yes
    ssh_key_bits:     2048
    ssh_key_file:     .ssh/id_rsa

