---
- name: Create user group
  ansible.builtin.group:
    name:     "{{ k3s_group }}"
    state:    present
    gid:      "{{ k3s_gid }}"

- name: Create user
  ansible.builtin.user:
    name:     "{{ k3s_user }}"
    shell:    /bin/bash
    createhome: yes
    comment:  Kubernetes Admin
    uid:      "{{ k3s_uid }}"
    group:    k3s
    password: "{{ k3s_passwd | password_hash('sha512') }}"
    state:    present

- name: Create a 2048-bit SSH key for user k3s in ~k3s/.ssh/id_rsa
  ansible.builtin.user:
    name:     k3s
    generate_ssh_key: yes
    ssh_key_bits:     2048
    ssh_key_file:     .ssh/id_rsa

- name: Create sudoers file for {{ k3s_user }}
  ansible.builtin.template:
    src:      templates/sudoers.j2
    dest:     /etc/sudoers.d/{{ k3s_user }}
    owner:    root
    group:    root
    mode:     '0400'

- name: Create /etc/sysctl.d/k8s.conf
  ansible.builtin.copy:
    src:      files/k8s.conf
    dest:     /etc/sysctl.d/k8s.conf
    owner:    root
    group:    root
    mode:     '0644'

- name: Create /etc/sysctl.d/99-kubernetes-cri.conf
  ansible.builtin.copy:
    src:      files/99-kubernetes-cri.conf
    dest:     /etc/sysctl.d/99-kubernetes-cri.conf
    owner:    root
    group:    root
    mode:     '0644'

- name: Create /etc/modules-load.d/containerd.conf
  ansible.builtin.copy:
    src:      files/containerd.conf
    dest:     /etc/modules-load.d/containerd.conf
    owner:    root
    group:    root
    mode:     '0644'

- name: Load K3s kernel modules
  shell:
       modprobe overlay
       modprobe br_netfilter

- name: Install K3s
  shell:
       curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.4+k3s1 sh -

- name: Install K3s SELinux packages
  yum:
    name:     "{{ packages }}"
    state:    latest
    update_cache: yes
  vars:
    packages:
    - container-selinux
    - selinux-policy-base
    - k3s-selinux

- name: Modify K3s systemctl unit file (Enable SELinux)
  ansible.builtin.lineinfile:
    path:     /etc/systemd/system/k3s.service
    regexp:   '^    server \\'
    line:     '    server --selinux \'
    owner:    root
    group:    root
    mode:     '0644'
    
- name: Modify K3s systemctl unit file (Disable servicelb)
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/k3s.service
#    regexp: '^    server --selinux \\'
    insertafter: '^    server --selinux \\'
    line: '    --disable servicelb'
    owner:    root
    group:    root
    mode:     '0644'
  notify:
  - Restart k3s


